// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: wzagbhksmfbvecqekzoe

class SupabaseConfig {
  static const String supabaseUrl = 'https://wzagbhksmfbvecqekzoe.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6YWdiaGtzbWZidmVjcWVrem9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3Nzg4MDYsImV4cCI6MjA4NjM1NDgwNn0.Z8wYw00JFBszBl3zQ72x4IsypEWADnBR2bhckHT2h_c';
}
